# Site settings
title: BCIT Game Development Club
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  building worlds
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate]

collections:
 - games



