# Site settings
title: BCIT Game Dev Club
email: bcitgamesdevclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  building worlds
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: BCITGamesDev
github_username:  github_username
facebook: https://www.facebook.com/groups/186612611443626/
github: https://github.com/BCIT-GameDevClub/BCIT-GameDevClub.github.io
gitter: https://gitter.im/BCIT-GameDevClub/BCIT-GameDevClub

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate]

collections:
 - games



